"""
<S> = "create" <G>
<G> = global <T> | local <T> | <U>
<T> = "temporary" <U> | "temp" <U>
<U>  = "unlogged" <TABLE> | <TABLE>
<TABLE> = "table" <TABLE IF NOT EXIST>
<TABLE IF NOT EXIST> = "table if not exist" <N> | <N>
<N> = <TABLE_NAME> ( <R> | <LIKE> | <TR>

<R> = <COLL_NAME> <TYPE> <COLLATE> <ROW_RESTRICT> <TRANSFER>
<TR> = <TABLE_RESTRICT> <TRANSFER>
<LIKE> = "like" <PARRENT_NAME> <COPY_METHOD> <TRANSFER>

<TRANSFER> = "," <TR> | "," <R> | "," <LIKE> | <ENT_ROWS_RESTRICTIONS_LIKE>

<ENT_ROWS_RESTRICTIONS_LIKE> = ) <I>
<I> = INHERITS (<PARRENT_NAME>) <PARTITION_BY> | <PARTITION_BY>
<PARTITION_BY> = "partition by" <PARTITION_METHOD> <FIELD_OR_EXPRESSION> <COLLATE> <OPERATOR_CLASS> <USING> | <USING>
<USING> = "using" <USING_METHOD> <WITH> | <WITH>
<WITH> = "with" <PARAMS> <ON_COMMIT> | "without oids" <ON_COMMIT> | <ON_COMMIT>
<ON_COMMIT> = "on commit" <ON_COMMIT_METHOD> <TABLESPACE> | <TABLESPACE>
<TABLESPACE> = "tablespace" <NAME> ; | ;


<USING_METHOD> = ...
<COPY_METHOD> = ...
<PARTITION_METHOD> = ....

<PARAMS> = ( <USUAL_PARAM>
<USUAL_PARAM> = <PARAM_NAME>="<PARAM_VALUE>" <PARAM_TRANSFER>
<PARAMS_TRANSFER> = , <USUAL_PARAM> | )


<COLLATE> = COLLATE <COLLATE_RULE>
<COLLATE_RULE> = <NAME>
<RESTRICT> = <NAME>
<TABLE_RESTRICT> = ...
<NAME> = \S+
"""

